// ********************************************************************************
// This file was generated by shader_conversion.py.
// ********************************************************************************

#include "OShaderID.h"

constexpr char glsl_OGlyph_fragment[] = R"(
#version 430 

varying mediump vec2 voTexcoord;
out lowp vec4 foOutColor;

uniform sampler2D uTexture;
uniform vec4 uColor;

void main(void) 
{
	foOutColor = vec4(1, 1, 1, texture2D(uTexture, voTexcoord).r) * uColor;
}
)";

constexpr char glsl_OGlyph_vertex[] = R"(
#version 430 

layout (location = 0) in vec4 aPosition;
varying mediump vec2 voTexcoord;
uniform vec2 uPosOffset;
uniform vec2 uScale;

void main(void) 
{
	gl_Position = vec4(aPosition.xy * uScale.xy + uPosOffset.xy, 0.0f, 1.0f);
	voTexcoord = aPosition.zw;
}
)";

constexpr char glsl_OMesh_fragment[] = R"(
#version 430

struct Material {
    vec3 color; 
};

layout(std430, binding = 0) readonly buffer MaterialBuffer {
    Material materials[];
};

flat in uint aMaterialIndex; 

out vec4 oColor;

void main()
{
	oColor = vec4(materials[aMaterialIndex].color, 1.0);
}

)";

constexpr char glsl_OMesh_vertex[] = R"(
#version 430

layout (location = 0) in vec4 aPosition;
layout (location = 3) in uint aMaterialIndex;

flat out uint oMaterialIndex;

uniform mat4 uMvpTransform;

void main()
{
	gl_Position = uMvpTransform * aPosition;
	oMaterialIndex = aMaterialIndex;
}

)";

void createShaderTable(OShaderSourceTable& aShaderTable)
{
	aShaderTable[{OGraphicsAPI::Type::OpenGL,OShaderObject::Type::Fragment,ORenderable::Type::Glyph}] = glsl_OGlyph_fragment;
	aShaderTable[{OGraphicsAPI::Type::OpenGL,OShaderObject::Type::Vertex,ORenderable::Type::Glyph}] = glsl_OGlyph_vertex;
	aShaderTable[{OGraphicsAPI::Type::OpenGL,OShaderObject::Type::Fragment,ORenderable::Type::Mesh}] = glsl_OMesh_fragment;
	aShaderTable[{OGraphicsAPI::Type::OpenGL,OShaderObject::Type::Vertex,ORenderable::Type::Mesh}] = glsl_OMesh_vertex;
}

